
[[language]]
name = "bash"
indent = { tab-width = 8, unit = "\t" }

[[language]]
name = "c"
indent = { tab-width = 4, unit = "\t" }
auto-format = false

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "\t" }
auto-format = false

[[language]]
name = "rust"
auto-format = false

